config/routes.rb
Rails.application.routes.draw do
  resources :measurement
  
  root 'page#map'
  
  get 'map' => 'page#map'
  get 'test' => 'page#test'
  get 'about' => 'page#about'
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
	validates :latitude, :longitude, :quality, numericality: true, presence: true
	validates :quality, inclusion: 0..10
	validates :latitude, inclusion: -90..90
	validates :longitude, inclusion: -180..180
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/measurement_controller.rb
class MeasurementController < ApplicationController
	def new
		@measurement = Measurement.new
	end
	
	def create
		measurement = Measurement.new(measurement_params)
		success = measurement.save()
		render plain: success
	end
	
	private
		def measurement_params
			params.require(:measurement).permit(:latitude, :longitude, :quality)
		end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def index
	end
	
	def test
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include NavLinkHelper
end

app/helpers/measurement_helper.rb
module MeasurementHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<%
nav = {
	'Map' => '/',
	'Speed Test' => test_path,
	'About' => about_path
	#'Add measurement' => new_measurement_path
}
%>

<!DOCTYPE html>
<html>
	<head>
		<title>Cellular Coverage | <%= yield :page_name %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag 'http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css' %>
		<%= stylesheet_link_tag 'non-sitewide/leaflet_map' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js' %>
		<%= javascript_include_tag '//speedof.me/api/api.js' %>
		<%= yield :head %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="main_container">
			<header>
				<h1>Cellular Coverage</h1>
			</header>
			<nav>
				<ul>
					<% nav.each do |name, link| %>
					<li><%= nav_link_to name, link %></li>
					<% end %>
					<br class="clear"/>
				</ul>
			</nav>
			<section>
				<%= yield %>
			</section>
			<footer>
			</footer>
		</div>
	</body>
</html>

app/views/measurement/new.html.erb
<h1>New Measurement</h1>
<%= form_for @measurement, validate: true, url: measurement_index_path do |f| %>
	<p>
		<%= f.label :latitude %><br>
		<%= f.text_field :latitude %>
	</p>
	<p>
		<%= f.label :longitude %><br>
		<%= f.text_field :longitude %>
	</p>
	<p>
		<%= f.label :quality %><br>
		<%= f.text_field :quality %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/page/about.html.erb
<% content_for :page_name do %>
	Map
<% end %>

<p>
	Repository: <a href="https://github.com/nitzel/cellularcoverage">https://github.com/nitzel/cellularcoverage</a>
	<ol>
		<li>
			<a href="https://goo.gl/aAUHOu"
				target="_blank">
				Presentation 18th of Nov 2015
			</a>
		</li>
		<li>
			<a href="https://goo.gl/PSS6Xd"
				target="_blank">
				Presentation 3rd of Dec 2015
			</a>
		</li>
		<li>
			<a href="https://goo.gl/PdYsjB"
				target="_blank">
				Presentation 14th of Dec 2015
			</a>
		</li>

	</ol>
</p>

app/views/page/map.html.erb
<% content_for :page_name do %>
	Map
<% end %>

<div id="map"></div>
<button onClick='locate(this)'>Locate</button>
<%= javascript_include_tag 'non-sitewide/leaflet_map' %>

app/views/page/test.html.erb
<% content_for :page_name do %>
	Speed Test
<% end %>

<% content_for :head do %>
	<%= javascript_include_tag 'non-sitewide/page/test/location', 'data-turbolinks-track' => false %>
	<%= javascript_include_tag 'non-sitewide/page/test/speed_test', 'data-turbolinks-track' => false %>
<% end %>

<div id="info"></div>
<div id="output"></div>
<div id="log"></div>
<button id="tester">Test network speed</button>

<script>
	//Do on load
	$(function(){
		on_load();
		$('#tester').click(function() {
			test_speed();
		});
	});
</script>